### ISSUE TITLE
Where to place diffuse color.

### ISSUE THREAD

**Issue by stavenko** [ebruneton/precomputed_atmospheric_scattering#11]
Hello.

How to correctly mix diffuse color of planet underneath atmosphere? 
I assume, there is something like 
```glsl
vec4 groundDiffuseColor = texture(screenspaceRenderedPlanet, uv);
```
In my shader.
How to mix them with ground_radiance?

**Comment by ebruneton** [comment]
You should replace kGroundAlbedo with groundDiffuseColor in

 ground_radiance = kGroundAlbedo * (1.0 / PI) * (
    sun_irradiance * GetSunVisibility(point, sun_direction) +
    sky_irradiance * GetSkyVisibility(point));

(in demo.glsl). groundDiffuseColor should be an albedo (i.e. fraction of incident light which is reflected, between 0 and 1).
