### ISSUE TITLE
dependencies

### ISSUE THREAD

**Issue by tpalli** [ebruneton/precomputed_atmospheric_scattering#16]
What is the math library used? My build fails like:

./atmosphere/reference/definitions.h:53:10: fatal error: math/angle.h: No such file or directory
 #include "math/angle.h"

**Comment by ebruneton** [comment]
These are git submodules. You need to do "git submodule init" and "git submodule update" (in the root directory) to get them.

**Comment by tpalli** [comment]
ok thanks!
