### ISSUE TITLE
Advice for combining aerial fog color

### ISSUE THREAD

**Issue by Sssyt** [ebruneton/precomputed_atmospheric_scattering#27]
Hi Eric, first of all, I´m sorry because this cannot be considered an issue. Your work is amazing and I really enjoyed implementing this. 👍 

I have problems combining the aerial fog color with the scene´s color. To my understanding, this should be a postprocess at the end of frame. 

However, if I feed final pixel color to retrieve the aerial fog I lose all "indirect lighting" contribution of my scene. This is due to the fact that for computing the sun irradiance your implementation is using the normal of the surface, therefore all surface which is pointing away from the sun looks black or almost black.

Is this even the correct way of doing it? I don´t know if I am missing something important. Thank you very much :)

**Comment by ebruneton** [comment]
Yes, it is possible to adapt the algorithm to use it as a postprocess effect. See for instance http://gamedevs.org/uploads/deferred-rendering-of-planetary-terrains-with-accurate-atmospheres.pdf.
