### ISSUE TITLE
Names of a few variables seem wrong

### ISSUE THREAD

**Issue by 10110111** [ebruneton/precomputed_atmospheric_scattering#29]
I'm studying the implementation of `GetSkyRadiance` function, and I'm having some difficulties understanding why the variables `r_p` and `m_p` (and `m_s_p` then too) are named with the `_p` in them [here](https://github.com/ebruneton/precomputed_atmospheric_scattering/blob/2bc8e4124e99bea7026fdd0a3933dd5c35ce6b5c/atmosphere/functions.glsl#L1744-L1747):
```glsl
    Length r_p =
        ClampRadius(atmosphere, sqrt(d * d + 2.0 * r * mu * d + r * r));
    Number mu_p = (r * mu + d) / r_p;
    Number mu_s_p = (r * mu_s + d * nu) / r_p;
```
It seems in [the documentation](https://ebruneton.github.io/precomputed_atmospheric_scattering/atmosphere/functions.glsl.html#transmittance_lookup) first two of these variables are called _r_<sub>_d_</sub> and _μ_<sub>_d_</sub>, since they refer not the the point **p**, but instead to **q** (which is at the distance _d_ from **p**).

Is this intentional? If yes, could you please explain why I'm wrong?

**Comment by ebruneton** [comment]
No, this is probably a copy paste effect. I agree that _d would be better here, because these variables are related to the point at distance d = shadow_length from the camera.

**Comment by 10110111** [comment]
OK, thanks.
