### ISSUE TITLE
Influence of ozone

### ISSUE THREAD

**Issue by mdkdy** [ebruneton/precomputed_atmospheric_scattering#34]
Here is effect of ozone in current implementation. On the left - enabled with default Dobson unit as in demo, 4 scattering orders and same Rayleigh scattering factor. On the left disabled. Gamma is enhanced a little.
![ozone](https://user-images.githubusercontent.com/26162577/74963966-e0730400-5412-11ea-87fb-f199cc741a00.png)
Here is comparison in Terragen 4.
![ozone2](https://user-images.githubusercontent.com/26162577/74963986-ea950280-5412-11ea-8e25-4850f3ca8655.jpg)
The right sides are similar. But I wonder about the ozone sides which differ - it gets more violet in current implementation than deep bluish as seen in Terragen or some real sky observation. 
I tried to regulate it by changing the Dobson unit but it seems to abruptly change from right to left colors. 
Can this be enhanced somewhat without increasing number of scattering orders much?  Thank you.

**Comment by mdkdy** [comment]
I just noticed my monitor low temperature setting which cuts off blue tints is exaggerating this a little :)

**Comment by ebruneton** [comment]
Doing the precomputations with [more than 3 wavelengths](https://github.com/ebruneton/precomputed_atmospheric_scattering/blob/master/atmosphere/model.h#L273) gives better results. This corresponds to the [PRECOMPUTED](https://github.com/ebruneton/precomputed_atmospheric_scattering/blob/master/atmosphere/demo/demo.h#L76) option in the demo. On the left is the result with the NONE option, on the right with the PRECOMPUTED option:

![img](https://user-images.githubusercontent.com/16741366/75180860-5346ec80-573d-11ea-8cd5-edcb2b82ae6c.jpg)

**Comment by mdkdy** [comment]
Thanks. I totally forgot about this option. I was using "APPROXIMATE" all the time. This indeed gives great results - especially with high Dobson unit.
![oz1](https://user-images.githubusercontent.com/26162577/75256864-6cef3f00-57e4-11ea-89f8-85e75d0167e6.png)
