### ISSUE TITLE
Online demo does not work

### ISSUE THREAD

**Issue by warmist** [ebruneton/precomputed_atmospheric_scattering#39]
I'm using Chrome 83.0.4103.116 on win 7 with AMD Radeon R9 200. Chrome console is filled (256 times) with `[.WebGL-000000000C0547A0] GL_INVALID_OPERATION: Two textures of different types use the same sampler location.`

**Comment by script526** [comment]
Doesn't work for me as well.

**Comment by ebruneton** [comment]
Unfortunately I don't have the necessary hardware & OS to reproduce this (the demo works fine for me). I committed a change which I guess (from the console log) could fix this, but I'm not sure. The online demo has been updated with this change.

**Comment by script526** [comment]
Now it's working. Thank you. Looks freaking good. Any helpers how to implement it in Unity? (C# and HLSL)

**Comment by warmist** [comment]
Just checked and it's fixed. Thank you!

**Comment by ebruneton** [comment]
Thanks! A Unity port is available here: https://github.com/Scrawk/Brunetons-Improved-Atmospheric-Scattering

**Comment by script526** [comment]
Thank you very much. Do you think it is going to be working in HDRP?
