### ISSUE TITLE
Atmospheric scattering and ozone

### ISSUE THREAD

**Issue by DrDrake** [ebruneton/precomputed_atmospheric_scattering#4]
Hi!
The new version has become much clearer and more correct. Great work! Have you thought about adding ozone accounting to your implementation? According to the developers of the Terragen (https://www.youtube.com/watch?v=z__WZOh1wXU), it has a significant effect on the appearance of the atmosphere. Gustav Bodare and Edvard Sandberg in their work (http://publications.lib.chalmers.se/records/fulltext/203057/203057.pdf) suggested that ozone should be taken into account not by a separate layer but by a distribution depending on the height (in "3.2.5 Transmittance"). As I understand their proposal is based on this http://skyrenderer.blogspot.se/2012/10/ozone-absorption.html article by Peter Kutz.

**Comment by ebruneton** [comment]
Thanks for your suggestion! I added support for the ozone layer. You can see its effect in the demo, with the 'o' key.

**Comment by DrDrake** [comment]
Thanks for implementation of it. You even added custom density profiles. Awesome!
