### ISSUE TITLE
Changing the color of the star

### ISSUE THREAD

**Issue by Iter-Ator** [ebruneton/precomputed_atmospheric_scattering#5]
Hi!

Thank you for the awesome demo.

Is it possible to change the spectrum (temperature) of the star?
The emittance at a given wavelength can be calculated from temperature by Planck's radiation law, but where should I give the calculated values to the Model, to use it as the star's color?

**Comment by ebruneton** [comment]
Yes, this is possible. You need to pass these values in the solar_irradiance vector parameter of the model constructor (see https://github.com/ebruneton/precomputed_atmospheric_scattering/blob/master/atmosphere/model.h, line 158). The demo uses the Sun spectrum (see https://github.com/ebruneton/precomputed_atmospheric_scattering/blob/master/atmosphere/demo/demo.cc, lines 158-171).
