### ISSUE TITLE
Sun angular size parameter

### ISSUE THREAD

**Issue by axtrend** [ebruneton/precomputed_atmospheric_scattering#9]
Currently sun angular size has effect on how fast direct radiance fades when sun hides beneath the horizon. 
http://i64.tinypic.com/14jyoh0.png
Correct me if I am wrong but should it also have effect on how fast sky radiance or indirect radiance fades into night or day during sunset or sunrise?

**Comment by ebruneton** [comment]
I updated the single scattering and direct irradiance computations to take the Sun angular size into account, but it makes no visible difference.
